name: labs-parser
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - openai
      - pillow
      - pandas
      - pdf2image
      - xlsxwriter
      - matplotlib
      - python-dotenv
